_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.0
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
eigenvalue_interval:
    value: 10
eigenvalue_type:
    value: raw_unnormalized
hidden_dim:
    value: 32
input_dim:
    value: 16
learning_rate:
    value: 1
matrix_type:
    value: low_rank_identity
np_seed:
    value: 12138
output_dim:
    value: 10
rank:
    value: 8
record_steps:
    value:
        - 5
        - 10
        - 15
        - 50
        - 100
        - 150
        - 200
        - 350
        - 500
steps:
    value: 500
target_rank:
    value: 8
top_k_pca_number:
    value: 50
torch_seed:
    value: 12138
variance:
    value: 0.01
wandb_project_name:
    value: Baseline
wandb_run_name:
    value: 3NN+GD+without activate function+traditional loss
