_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.0
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 50
hidden_dim:
    value: 200
input_dim:
    value: 784
learning_rate:
    value: 0.01
np_seed:
    value: 0
output_dim:
    value: 10
record_steps:
    value:
        - 100
        - 500
        - 1000
        - 3000
        - 5000
        - 10000
        - 15000
        - 20000
steps:
    value: 20000
test_samples:
    value: 5000
top_k_pca_number:
    value: 10
torch_seed:
    value: 0
train_samples:
    value: 5000
wandb_project_name:
    value: MNIST
wandb_run_name:
    value: 3 NN MLP+Tanh+SGD+MSE+MNIST-5k(tiny space set up)(Three models)
